#############################################################################
# Makefile for building: qml-player.app/Contents/MacOS/qml-player
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  qml-player.pro
# Template: app
# Command: /Users/dodo/Projekte/sdk/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile qml-player.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtWebSockets.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib
QMAKE         = /Users/dodo/Projekte/sdk/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qml-player1.0.0
DISTDIR = /Users/dodo/Projekte/top/qml-player-sub/.tmp/qml-player1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib -framework VLCQtCore -framework VLCQtWidgets -framework VLCQtQml -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQuickControls2 -framework QtQuick -framework QtQml -framework QtNetwork -framework QtWebSockets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/cpp/main.cpp \
		src/cpp/cmdclient.cpp \
		src/cpp/backend.cpp qrc_qml.cpp \
		moc_cmdclient.cpp \
		moc_backend.cpp
OBJECTS       = main.o \
		cmdclient.o \
		backend.o \
		qrc_qml.o \
		moc_cmdclient.o \
		moc_backend.o
DIST          = ../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		qml-player.pro src/cpp/cmdclient.h \
		src/cpp/backend.h src/cpp/main.cpp \
		src/cpp/cmdclient.cpp \
		src/cpp/backend.cpp
QMAKE_TARGET  = qml-player
DESTDIR       = 
TARGET        = qml-player.app/Contents/MacOS/qml-player


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d qml-player.app/Contents/MacOS/ || mkdir -p qml-player.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qml-player.pro ../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../sdk/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		qml-player.pro \
		qml.qrc \
		../../sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile qml-player.pro
../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../sdk/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../sdk/Qt/5.7/clang_64/mkspecs/features/lex.prf:
qml-player.pro:
qml.qrc:
../../sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/QtQuickControls2.prl:
../../sdk/Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../sdk/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../sdk/Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../sdk/Qt/5.7/clang_64/lib/QtWebSockets.framework/QtWebSockets.prl:
../../sdk/Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile qml-player.pro

qmake_all: FORCE

qml-player.app/Contents/PkgInfo: 
	@test -d qml-player.app/Contents || mkdir -p qml-player.app/Contents
	@$(DEL_FILE) qml-player.app/Contents/PkgInfo
	@echo "APPL????" > qml-player.app/Contents/PkgInfo
qml-player.app/Contents/Resources/empty.lproj: 
	@test -d qml-player.app/Contents/Resources || mkdir -p qml-player.app/Contents/Resources
	@touch qml-player.app/Contents/Resources/empty.lproj
	
qml-player.app/Contents/Info.plist: 
	@test -d qml-player.app/Contents || mkdir -p qml-player.app/Contents
	@$(DEL_FILE) qml-player.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.heim.qml-player,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qml-player,g" -e "s,@LIBRARY@,qml-player,g" -e "s,@TYPEINFO@,????,g" ../../sdk/Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >qml-player.app/Contents/Info.plist

all: Makefile \
		qml-player.app/Contents/PkgInfo \
		qml-player.app/Contents/Resources/empty.lproj \
		qml-player.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/cpp/cmdclient.h src/cpp/backend.h $(DISTDIR)/
	$(COPY_FILE) --parents src/cpp/main.cpp src/cpp/cmdclient.cpp src/cpp/backend.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qml-player.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../sdk/Qt/5.7/clang_64/bin/rcc \
		src/qml/Model.qml \
		src/qml/FlatSourceModel.qml \
		src/qml/Drawer.qml \
		src/qml/VisibleAnimation.qml \
		src/qml/CmdClient.qml \
		src/qml/main.qml \
		src/qml/components/SourceList.qml \
		src/qml/components/VisibleAnimation.qml \
		src/qml/components/SourceListView.qml \
		src/qml/components/SourceMenu.qml \
		src/qml/components/MenuPane.qml
	/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_cmdclient.cpp moc_backend.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cmdclient.cpp moc_backend.cpp
moc_cmdclient.cpp: ../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		src/cpp/cmdclient.h \
		../../sdk/Qt/5.7/clang_64/bin/moc
	/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/dodo/Projekte/top/qml-player-sub -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtWebSockets.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib src/cpp/cmdclient.h -o moc_cmdclient.cpp

moc_backend.cpp: ../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QProcessEnvironment \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		src/cpp/backend.h \
		../../sdk/Qt/5.7/clang_64/bin/moc
	/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/dodo/Projekte/top/qml-player-sub -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtWebSockets.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/dodo/Projekte/sdk/Qt/5.7/clang_64/lib src/cpp/backend.h -o moc_backend.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: src/cpp/main.cpp ../../sdk/Qt/5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../sdk/Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../sdk/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QProcessEnvironment \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers/QQuickStyle \
		../../sdk/Qt/5.7/clang_64/lib/QtQuickControls2.framework/Headers/qquickstyle.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		src/cpp/cmdserver.h \
		src/cpp/cmdclient.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		src/cpp/backend.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/cpp/main.cpp

cmdclient.o: src/cpp/cmdclient.cpp src/cpp/CmdClient.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmdclient.o src/cpp/cmdclient.cpp

backend.o: src/cpp/backend.cpp src/cpp/backend.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QProcessEnvironment \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../sdk/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend.o src/cpp/backend.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_cmdclient.o: moc_cmdclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmdclient.o moc_cmdclient.cpp

moc_backend.o: moc_backend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backend.o moc_backend.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qml-player/bin || mkdir -p $(INSTALL_ROOT)/opt/qml-player/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/qml-player/bin/qml-player.app
	
	-$(INSTALL_DIR) qml-player.app $(INSTALL_ROOT)/opt/qml-player/bin/qml-player.app
	-$(STRIP) $(INSTALL_ROOT)/opt/qml-player/bin/qml-player.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/qml-player/bin/qml-player.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qml-player/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

